export const SET_SUNS = 'SET_SUNS'
export const SET_USERS = 'SET_USERS'
export const GET_EMAIL_AND_PW = 'GET_EMAIL_AND_PW'
export const FIND_MATCHED_IDS = 'FIND_MATCHED_IDS'
export const CURRENT_USER_ID = 'CURRENT_USER_ID'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const ENABLE_CHAT = 'ENABLE_CHAT'
export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS'
export const DELETE_USER = 'DELETE_USER'
export const FIND_MATCHES = 'FIND_MATCHES'
export const FIND_MATCHED_USERS = 'FIND_MATCHED_USERS'
export const ALL_UNDECLINED_MATCHES = 'ALL_UNDECLINED_MATCHES'
export const ALL_UNDECLINED_MATCHED_USERS = 'ALL_UNDECLINED_MATCHED_USERS'
export const VIEW_MATCH = 'VIEW_MATCH'
export const ACCEPT_MATCH = 'ACCEPT_MATCH'
export const ACCEPT_MATCHED_USER = 'ACCEPT_MATCHED_USER'
export const DECLINE_MATCH = 'DECLINE_MATCH'
export const DECLINE_MATCHED_USER = 'DECLINE_MATCHED_USER'
export const DECLINE_PENDING_MATCH = 'DECLINE_PENDING_MATCH'
export const DECLINE_PENDING_MATCHED_USER = 'DECLINE_PENDING_MATCHED_USER'
export const UPDATE_MATCHED_USERS = 'UPDATE_MATCHED_USERS'
export const UPDATE_MATCHES = 'UPDATE_MATCHES'
export const FIND_ACCEPTED = 'FIND_ACCEPTED'
export const FIND_ACCEPTED_USERS = 'FIND_ACCEPTED_USERS'
export const GET_CHATS = 'GET_CHATS'
export const SAVE_CHATS = 'SAVE_CHATS'
export const SET_RECEIVER_ID = 'SET_RECEIVER_ID'
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT'
export const SAVE_CURRENT_CHAT = 'SAVE_CURRENT_CHAT'
export const ERASE_CURRENT_CHAT = 'ERASE_CURRENT_CHAT'
export const API_ROOT = 'http://localhost:3000/api/v1'
export const API_WS_ROOT = 'ws://localhost:3000/api/v1/cable'
export const HEADERS = {
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  'Authorization': localStorage.getItem('token')
}
